version: "3"

services:
  app:
    build: .
    ports:
      - 5050:5050
    environment:
      - ${OPENAI_API_KEY}
      - ${YT_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ytfull
    volumes:
      - ./init.db.sql:/docker-entrypoint-initdb.d/init.db.sql
    ports:
      - 5432:5432